/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StorybookIndexRouteImport } from './routes/storybook/index'
import { Route as StorybookTestRouteImport } from './routes/storybook/test'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorybookIndexRoute = StorybookIndexRouteImport.update({
  id: '/storybook/',
  path: '/storybook/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorybookTestRoute = StorybookTestRouteImport.update({
  id: '/storybook/test',
  path: '/storybook/test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/storybook/test': typeof StorybookTestRoute
  '/storybook/': typeof StorybookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/storybook/test': typeof StorybookTestRoute
  '/storybook': typeof StorybookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/storybook/test': typeof StorybookTestRoute
  '/storybook/': typeof StorybookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/storybook/test' | '/storybook/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/storybook/test' | '/storybook'
  id: '__root__' | '/' | '/about' | '/storybook/test' | '/storybook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StorybookTestRoute: typeof StorybookTestRoute
  StorybookIndexRoute: typeof StorybookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storybook/': {
      id: '/storybook/'
      path: '/storybook'
      fullPath: '/storybook/'
      preLoaderRoute: typeof StorybookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storybook/test': {
      id: '/storybook/test'
      path: '/storybook/test'
      fullPath: '/storybook/test'
      preLoaderRoute: typeof StorybookTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StorybookTestRoute: StorybookTestRoute,
  StorybookIndexRoute: StorybookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
