/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanningPokerIndexRouteImport } from './routes/planning-poker/index'
import { Route as PlanningPokerRoomIdRouteImport } from './routes/planning-poker/$roomId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningPokerIndexRoute = PlanningPokerIndexRouteImport.update({
  id: '/planning-poker/',
  path: '/planning-poker/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningPokerRoomIdRoute = PlanningPokerRoomIdRouteImport.update({
  id: '/planning-poker/$roomId',
  path: '/planning-poker/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/planning-poker/$roomId': typeof PlanningPokerRoomIdRoute
  '/planning-poker/': typeof PlanningPokerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/planning-poker/$roomId': typeof PlanningPokerRoomIdRoute
  '/planning-poker': typeof PlanningPokerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/planning-poker/$roomId': typeof PlanningPokerRoomIdRoute
  '/planning-poker/': typeof PlanningPokerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/planning-poker/$roomId' | '/planning-poker/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/planning-poker/$roomId' | '/planning-poker'
  id: '__root__' | '/' | '/about' | '/planning-poker/$roomId' | '/planning-poker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PlanningPokerRoomIdRoute: typeof PlanningPokerRoomIdRoute
  PlanningPokerIndexRoute: typeof PlanningPokerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning-poker/': {
      id: '/planning-poker/'
      path: '/planning-poker'
      fullPath: '/planning-poker/'
      preLoaderRoute: typeof PlanningPokerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning-poker/$roomId': {
      id: '/planning-poker/$roomId'
      path: '/planning-poker/$roomId'
      fullPath: '/planning-poker/$roomId'
      preLoaderRoute: typeof PlanningPokerRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PlanningPokerRoomIdRoute: PlanningPokerRoomIdRoute,
  PlanningPokerIndexRoute: PlanningPokerIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
